image: docker/compose:latest
services:
  - docker:dind
before_script:
  - docker info
  - docker-compose version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - report
  - deploy

build templates:
  stage: build
  script:
    # Retrieve main output if we are in a merge request
    - |
      if test -n "$CI_MERGE_REQUEST_ID"; then
           echo "Target branch is $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
           ref=$(git ls-remote origin refs/heads/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME | awk '{print $1}')
           echo "Target branch ref is $ref"
           git cat-file -e $ref || git fetch -q origin $ref
           ref=$(git merge-base $ref HEAD)
           image=${CI_REGISTRY_IMAGE}:outputs-$ref
           echo "Common ancestor with $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME is $ref"
           echo "Pulling docker image $image"
           docker pull $image
           echo "Extract to output-main"
           docker container create --name tmp_$$ $image nothing
           mkdir output-main
           docker container export tmp_$$ \
             | tar -C output-main -xf - --strip-components=1 --wildcards output/\*
           docker container rm tmp_$$
      fi
    # Build templates
    - docker-compose rm -s -f -v
    - docker image rm --no-prune cmdb_jerikan-ci:latest || true
    - docker-compose pull
    - SERVICE=jerikan-ci ./run build $(test -n "$CI_MERGE_REQUEST_ID" && echo --diff=output-main)
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID
  cache:
    paths:
      - .cache~
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    expose_as: configurations and report
    when: always
    expire_in: 3 months
    paths:
      - output/
    reports:
      junit: output/junit.xml

push artifacts to registry:
  stage: report
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_MERGE_REQUEST_ID
  dependencies:
    - build templates
  script:
    - tar zcf - output | docker image import - $CI_REGISTRY_IMAGE:outputs-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:outputs-$CI_COMMIT_SHA

diff generated:
  stage: report
  rules:
    - if: $CI_MERGE_REQUEST_ID
  dependencies:
    - build templates
  script:
    - docker-compose build diff2html
    - (cat output/*/diff.txt; echo) | docker-compose run --rm diff2html > diff.html
  artifacts:
    expose_as: differences with main
    expire_in: 1 month
    paths:
      - diff.html
